use_frameworks!

target 'InvertedSwift_Example' do
  pod 'InvertedSwift', :path => '../'

  target 'InvertedSwift_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
